# Generated by Django 4.0.3 on 2023-10-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100, unique=True, verbose_name='Название операции')),
                ('N_count', models.FloatField(null=True, verbose_name='Общее число выполненных операций 𝑗-го вида')),
                ('n_error', models.FloatField(null=True, verbose_name='Число ошибок')),
                ('k', models.FloatField(null=True, verbose_name='Число выполненных операций 𝑗-го вида')),
                ('Pk', models.FloatField(null=True, verbose_name='Вероятность выдачи сигнала системой контроля')),
                ('Pob', models.FloatField(null=True, verbose_name='Вероятность обнаружения диспетчером сигнала контроля')),
                ('Pi', models.FloatField(null=True, verbose_name='Вероятность исправления ошибочных действий при повторном выполнении операции')),
            ],
            options={
                'verbose_name': 'Деятельность',
                'verbose_name_plural': 'Деятельность',
            },
        ),
    ]
