# Generated by Django 4.0.3 on 2023-11-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survival_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='failed_obj',
            field=models.IntegerField(verbose_name='Число объектов, для которых произошёл исход'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='probability',
            field=models.FloatField(verbose_name='Вероятность исхода'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='surviving_obj',
            field=models.IntegerField(verbose_name='Число объектов, доживающих до t'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='time',
            field=models.IntegerField(verbose_name='Момент времени'),
        ),
    ]
