# Generated by Django 4.0.3 on 2023-11-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название схемы')),
                ('type', models.CharField(max_length=4, verbose_name='Тип схемы')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=100, verbose_name='Название элемента')),
                ('operating_time', models.FloatField(null=True, verbose_name='Наработка(в часах)')),
                ('date', models.DateField(null=True, verbose_name='Дата установки')),
                ('sub_system', models.FloatField(null=True, verbose_name='Номер подсистемы')),
                ('number', models.FloatField(null=True, verbose_name='Номер элемента в системе')),
            ],
            options={
                'verbose_name': 'Элемент схемы',
                'verbose_name_plural': 'Элементы схемы',
                'unique_together': {('sub_system', 'number')},
            },
        ),
    ]
