# Generated by Django 4.0.3 on 2023-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='operating_time',
            field=models.FloatField(null=True, verbose_name='Наработка(в днях)'),
        ),
    ]
