# Generated by Django 4.0.3 on 2023-11-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MillsParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_N', models.IntegerField(verbose_name='Естественные ошибки N')),
                ('low_n', models.IntegerField(verbose_name='Обнаруженные естественные ошибки n')),
                ('high_M', models.IntegerField(verbose_name='Искусственные ошибки M')),
                ('low_m', models.IntegerField(verbose_name='Обнаруженные искусственные ошибки m')),
            ],
            options={
                'verbose_name': 'Миллс параметр',
                'verbose_name_plural': 'Миллс параметры',
            },
        ),
    ]
