# Generated by Django 4.0.3 on 2023-11-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='millsparam',
            name='high_N',
        ),
    ]
